name: Build Test Deploy Workflow
on: 
  push:
    branches: main
  workflow_dispatch:
  issues:
    types: opened
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/GitHubWorkFlows/') }}
      - name: Install dependencies
        run: dotnet restore GitHubWorkFlows/GitHubWorkFlows.sln
      - name: Test with the dotnet CLI
        run: dotnet test GitHubWorkFlows/GitHubWorkFlows.sln
        
  build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/GitHubWorkFlows/') }}
    # - name: Install dependencies
    #   run: dotnet restore GitHubWorkFlows/GitHubWorkFlows.sln
    - name: Build
      run: dotnet build GitHubWorkFlows/GitHubWorkFlows.sln
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Main API Build Artifacts
        path: GitHubWorkFlows/MainAPI/bin/Debug/net8.0/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: Main API Build Artifacts
    - name: Deploy
      run: echo "Deploying..."