name: Build Test Deploy Workflow
on: 
  push:
    branches: main
  workflow_dispatch:
  issues:
    types: opened
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Test with the dotnet CLI
      run: dotnet test
    - name: Build
      run: dotnet build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Main API Build Artifacts
        path: GitHubWorkFlows/MainAPI/bin/Debug/net8.0/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: Main API Build Artifacts
    - name: Deploy
      run: echo "Deploying..."